In [1]:
import pandas as pd
import numpy as np

In [2]:


import os

print("Current Working Directory:")
print(os.getcwd())

print("\nFiles and Folders:")
print(os.listdir())

Current Working Directory:
C:\Users\lenovo\OneDrive\Desktop\Banking Customer 360 Analytics

Files and Folders:
['.ipynb_checkpoints', '01_Dataset_Verification.ipynb', '01_Raw Data', '02_Cleaned Data', '03_Python', '04_SQL', '05_Excel', '06_Power BI', 'Documentation', 'Insights', 'README.md']

In [3]:

import os

print("Current Location:")
print(os.getcwd())

print("\nFolder Contents:")
for item in os.listdir():
    print(item)

Current Location:
C:\Users\lenovo\OneDrive\Desktop\Banking Customer 360 Analytics

Folder Contents:
.ipynb_checkpoints
01_Dataset_Verification.ipynb
01_Raw Data
02_Cleaned Data
03_Python
04_SQL
05_Excel
06_Power BI
Documentation
Insights
README.md

In [4]:

import os

print("Raw Data Folder Contents:")

for item in os.listdir("01_Raw Data"):
    print(item)

Raw Data Folder Contents:
bank_churn_dataset.csv

In [5]:
df = pd.read_csv("01_Raw Data/bank_churn_dataset.csv")

In [6]:
print(df.shape)

(80000, 26)

In [7]:
import os

print("Raw Data Folder Contents:")

for item in os.listdir("01_Raw Data"):
    print(item)

Raw Data Folder Contents:
bank_churn_dataset.csv

In [8]:
import pandas as pd

df = pd.read_csv("01_Raw Data/bank_churn_dataset.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (80000, 26)

In [9]:
print("Column Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Column Names:
['id', 'full_name', 'credit_sco', 'gender', 'age', 'occupation', 'balance', 'monthly_ir', 'address', 'origin_province', 'tenure_ye', 'married', 'nums_card', 'nums_service', 'active_member', 'last_active_date', 'last_transaction_month', 'created_date', 'exit', 'customer_segment', 'engagement_score', 'loyalty_level', 'digital_behavior', 'risk_score', 'risk_segment', 'cluster_group']

Data Types:
id                          int64
full_name                     str
credit_sco                  int64
gender                        str
age                         int64
occupation                    str
balance                     int64
monthly_ir                  int64
address                       str
origin_province               str
tenure_ye                   int64
married                     int64
nums_card                   int64
nums_service                int64
active_member                bool
last_active_date              str
last_transaction_month      int64
created_date                  str
exit                         bool
customer_segment              str
engagement_score            int64
loyalty_level                 str
digital_behavior              str
risk_score                float64
risk_segment                  str
cluster_group               int64
dtype: object

In [10]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Missing Values:
id                        0
full_name                 0
credit_sco                0
gender                    0
age                       0
occupation                0
balance                   0
monthly_ir                0
address                   0
origin_province           0
tenure_ye                 0
married                   0
nums_card                 0
nums_service              0
active_member             0
last_active_date          0
last_transaction_month    0
created_date              0
exit                      0
customer_segment          0
engagement_score          0
loyalty_level             0
digital_behavior          0
risk_score                0
risk_segment              0
cluster_group             0
dtype: int64

Duplicate Rows:
0

In [11]:
print(df.dtypes)

id                          int64
full_name                     str
credit_sco                  int64
gender                        str
age                         int64
occupation                    str
balance                     int64
monthly_ir                  int64
address                       str
origin_province               str
tenure_ye                   int64
married                     int64
nums_card                   int64
nums_service                int64
active_member                bool
last_active_date              str
last_transaction_month      int64
created_date                  str
exit                         bool
customer_segment              str
engagement_score            int64
loyalty_level                 str
digital_behavior              str
risk_score                float64
risk_segment                  str
cluster_group               int64
dtype: object

In [12]:
print(df.dtypes.to_string())

id                          int64
full_name                     str
credit_sco                  int64
gender                        str
age                         int64
occupation                    str
balance                     int64
monthly_ir                  int64
address                       str
origin_province               str
tenure_ye                   int64
married                     int64
nums_card                   int64
nums_service                int64
active_member                bool
last_active_date              str
last_transaction_month      int64
created_date                  str
exit                         bool
customer_segment              str
engagement_score            int64
loyalty_level                 str
digital_behavior              str
risk_score                float64
risk_segment                  str
cluster_group               int64

In [13]:
categorical_cols = df.select_dtypes(include=["str"]).columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print("Unique Count:", df[col].nunique())
    print("Top Values:")
    print(df[col].value_counts().head(10))

--- full_name ---
Unique Count: 5100
Top Values:
full_name
Lê Minh Quang        42
Phạm Anh Quang       41
Vũ Đức Quang         41
Mai Thanh Quang      40
Mai Hữu Quang        38
Bùi Anh Quang        38
Lê Thu Quang         37
Trần Minh Quang      37
Bùi Minh Quang       37
Dương Hoàng Quang    37
Name: count, dtype: int64

--- gender ---
Unique Count: 2
Top Values:
gender
male      40008
female    39992
Name: count, dtype: int64

--- occupation ---
Unique Count: 10
Top Values:
occupation
Kỹ sư/Chuyên viên IT             8199
Nội trợ/Sinh viên                8096
Nhân viên văn phòng/Công chức    8061
Quản lý/Lãnh đạo                 7986
Giáo viên/Giảng viên             7975
Kế toán/Tài chính                7972
Lao động phổ thông               7968
Kinh doanh/Bán hàng              7967
Chủ Doanh nghiệp nhỏ             7915
Hưu trí                          7861
Name: count, dtype: int64

--- address ---
Unique Count: 16
Top Values:
address
Linh Trung (TP Thủ Đức)         5085
Phường 7 (Q7)                   5069
Xã Vĩnh Lộc A (BC)              5053
Phường Quang Trung (GV)         5043
Phường An Hội (BT)              5038
Phường 2 (Tân Bình)             5026
Thị trấn Tân Túc (BC)           5020
Phường Tân Định (Q1)            5015
Phường Chợ Quán (Q5)            5014
Phường Tân Sơn Nhì (Tân Phú)    5002
Name: count, dtype: int64

--- origin_province ---
Unique Count: 9
Top Values:
origin_province
TP. Hồ Chí Minh      40148
Bình Dương            8008
Đồng Nai              7888
Long An               4862
Tỉnh khác             4808
Tiền Giang            4080
Bà Rịa - Vũng Tàu     3951
Cần Thơ               3161
Hà Nội                3094
Name: count, dtype: int64

--- last_active_date ---
Unique Count: 1614
Top Values:
last_active_date
01/07/2025    388
27/06/2025    329
30/06/2025    325
26/06/2025    298
28/06/2025    295
29/06/2025    285
25/06/2025    276
24/06/2025    267
13/06/2025    258
23/06/2025    255
Name: count, dtype: int64

--- created_date ---
Unique Count: 1643
Top Values:
created_date
09/05/2023    76
22/06/2022    71
20/12/2023    71
27/11/2024    70
25/11/2022    68
15/10/2021    68
09/10/2023    68
15/12/2021    67
10/03/2025    67
22/04/2023    66
Name: count, dtype: int64

--- customer_segment ---
Unique Count: 4
Top Values:
customer_segment
Emerging    31662
Mass        21436
Priority    15692
Affluent    11210
Name: count, dtype: int64

--- loyalty_level ---
Unique Count: 3
Top Values:
loyalty_level
Bronze    69252
Silver     8977
Gold       1771
Name: count, dtype: int64

--- digital_behavior ---
Unique Count: 2
Top Values:
digital_behavior
offline    62824
mobile     17176
Name: count, dtype: int64

--- risk_segment ---
Unique Count: 2
Top Values:
risk_segment
Low       74753
Medium     5247
Name: count, dtype: int64

In [14]:
print("Numerical Columns:")
print(df.select_dtypes(include="number").columns.tolist())

print("\nNumerical Summary:")
print(df.select_dtypes(include="number").describe().T)

Numerical Columns:
['id', 'credit_sco', 'age', 'balance', 'monthly_ir', 'tenure_ye', 'married', 'nums_card', 'nums_service', 'last_transaction_month', 'engagement_score', 'risk_score', 'cluster_group']

Numerical Summary:
                          count          mean           std           min  \
id                      80000.0  4.000050e+04  2.309416e+04  1.000000e+00
credit_sco              80000.0  6.843211e+02  5.116973e+01  4.950000e+02
age                     80000.0  4.938186e+01  1.506748e+01  2.000000e+01
balance                 80000.0  6.118320e+07  8.868620e+07  4.086630e+05
monthly_ir              80000.0  3.778820e+07  3.655107e+07  3.000000e+06
tenure_ye               80000.0  1.777250e+00  1.315828e+00  0.000000e+00
married                 80000.0  9.708250e-01  6.946977e-01  0.000000e+00
nums_card               80000.0  2.634688e+00  1.218556e+00  1.000000e+00
nums_service            80000.0  3.564425e+00  2.002448e+00  1.000000e+00
last_transaction_month  80000.0  8.831755e+06  3.378683e+07  0.000000e+00
engagement_score        80000.0  3.172540e+01  2.347486e+01  7.000000e+00
risk_score              80000.0  2.692600e-01  9.189084e-02  1.730000e-02
cluster_group           80000.0  1.971037e+00  1.040763e+00  1.000000e+00

                                 25%           50%           75%           max
id                      2.000075e+04  4.000050e+04  6.000025e+04  8.000000e+04
credit_sco              6.490000e+02  6.820000e+02  7.180000e+02  8.000000e+02
age                     3.800000e+01  4.700000e+01  5.800000e+01  9.000000e+01
balance                 1.462592e+07  3.090276e+07  6.960994e+07  1.000000e+09
monthly_ir              1.400000e+07  2.300000e+07  4.700000e+07  2.160000e+08
tenure_ye               1.000000e+00  2.000000e+00  3.000000e+00  4.000000e+00
married                 1.000000e+00  1.000000e+00  1.000000e+00  3.000000e+00
nums_card               2.000000e+00  2.000000e+00  3.000000e+00  5.000000e+00
nums_service            2.000000e+00  3.000000e+00  5.000000e+00  8.000000e+00
last_transaction_month  0.000000e+00  0.000000e+00  0.000000e+00  6.000000e+08
engagement_score        1.600000e+01  2.200000e+01  3.800000e+01  1.000000e+02
risk_score              2.004000e-01  2.774000e-01  3.389000e-01  5.404000e-01
cluster_group           1.000000e+00  2.000000e+00  2.000000e+00  4.000000e+00

In [15]:
print("married values:")
print(df["married"].value_counts().sort_index())

print("\nlast_transaction_month values:")
print(df["last_transaction_month"].value_counts().sort_index())

print("\ncluster_group values:")
print(df["cluster_group"].value_counts().sort_index())

married values:
married
0    16480
1    53399
2     6096
3     4025
Name: count, dtype: int64

last_transaction_month values:
last_transaction_month
0            62824
500000           5
532090           1
545259           1
550721           1
             ...
575487877        1
583472425        1
583866727        1
595791141        1
600000000       38
Name: count, Length: 17132, dtype: int64

cluster_group values:
cluster_group
1    31017
2    33785
3     1696
4    13502
Name: count, dtype: int64

In [18]:
print("Sample rows:")
print(df[["married", "last_transaction_month", "cluster_group"]].head(20))

Sample rows:
    married  last_transaction_month  cluster_group
0         2                91038993              4
1         1                 3255569              2
2         0                       0              4
3         0                       0              4
4         1                       0              2
5         1                       0              2
6         1                       0              2
7         1                 6462745              2
8         1                       0              2
9         1                       0              4
10        1                       0              2
11        1                       0              2
12        1                       0              2
13        2                       0              1
14        1                       0              4
15        0                       0              4
16        1                31706109              1
17        1                       0              1
18        1                 2322197              1
19        0                       0              4

In [19]:
print("\nRows with unusual last_transaction_month:")
print(
    df[df["last_transaction_month"] > 100000]
    [["id", "last_transaction_month"]]
    .head(20)
)

Rows with unusual last_transaction_month:
    id  last_transaction_month
0    1                91038993
1    2                 3255569
7    8                 6462745
16  17                31706109
18  19                 2322197
25  26                 5168697
29  30                15971549
30  31                17775197
34  35                46492280
36  37                15065550
40  41                55062791
44  45                 4415684
47  48                23846449
52  53                44355030
55  56               103126977
58  59                15416405
65  66                 4030519
69  70                59862993
85  86                 6528612
92  93               225966261

In [20]:
# Check suspicious columns in detail

check_cols = [
    "married",
    "last_transaction_month",
    "balance",
    "monthly_ir",
    "cluster_group"
]

for col in check_cols:
    print(f"\n========== {col} ==========")
    print("Data Type:", df[col].dtype)
    print("Unique Values:", df[col].nunique())
    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())
    print("\nTop 10 Values:")
    print(df[col].value_counts().head(10))

========== married ==========
Data Type: int64
Unique Values: 4
Minimum: 0
Maximum: 3

Top 10 Values:
married
1    53399
0    16480
2     6096
3     4025
Name: count, dtype: int64

========== last_transaction_month ==========
Data Type: int64
Unique Values: 17132
Minimum: 0
Maximum: 600000000

Top 10 Values:
last_transaction_month
0            62824
600000000       38
500000           5
15774271         2
12152772         2
4727198          2
5592504          2
91038993         1
3255569          1
6462745          1
Name: count, dtype: int64

========== balance ==========
Data Type: int64
Unique Values: 79920
Minimum: 408663
Maximum: 1000000000

Top 10 Values:
balance
1000000000    50
36274615       2
9930029        2
43700745       2
58441232       2
15927405       2
12292938       2
29612098       2
6261095        2
7477733        2
Name: count, dtype: int64

========== monthly_ir ==========
Data Type: int64
Unique Values: 209
Minimum: 3000000
Maximum: 216000000

Top 10 Values:
monthly_ir
13000000    2780
12000000    2763
14000000    2756
15000000    2658
11000000    2567
16000000    2514
10000000    2406
9000000     2293
17000000    2220
18000000    2114
Name: count, dtype: int64

========== cluster_group ==========
Data Type: int64
Unique Values: 4
Minimum: 1
Maximum: 4

Top 10 Values:
cluster_group
2    33785
1    31017
4    13502
3     1696
Name: count, dtype: int64

In [21]:
# Inspect suspicious records

cols_to_check = [
    "id",
    "married",
    "balance",
    "monthly_ir",
    "last_transaction_month",
    "cluster_group",
    "customer_segment",
    "loyalty_level",
    "digital_behavior",
    "risk_segment"
]

print("Rows where last_transaction_month is unusually high:")
display(
    df.loc[
        df["last_transaction_month"] > 100000000,
        cols_to_check
    ].head(20)
)

Rows where last_transaction_month is unusually high:

,id,married,balance,monthly_ir,last_transaction_month,cluster_group,customer_segment,loyalty_level,digital_behavior,risk_segment
55,56,1,79111754,65000000,103126977,3,Priority,Silver,mobile,Low
92,93,0,99922101,88000000,225966261,3,Priority,Bronze,mobile,Low
170,171,3,43659761,48000000,145089562,3,Affluent,Gold,mobile,Low
181,182,1,100134599,68000000,143510937,3,Priority,Silver,mobile,Low
242,243,0,71315175,123000000,385050528,3,Priority,Bronze,mobile,Low
277,278,1,73743218,75000000,188088795,3,Priority,Bronze,mobile,Low
297,298,3,27072351,36000000,106959518,1,Affluent,Bronze,mobile,Low
415,416,1,31227142,33000000,135271268,3,Emerging,Bronze,mobile,Low
421,422,3,40269957,107000000,287744630,3,Priority,Bronze,mobile,Low
606,607,1,117161262,130000000,158286240,3,Priority,Bronze,mobile,Low
607,608,1,82716497,157000000,204386941,3,Priority,Bronze,mobile,Low
639,640,1,58074709,75000000,109501026,3,Priority,Bronze,mobile,Low
691,692,1,71288375,113000000,131101929,3,Priority,Bronze,mobile,Low
761,762,1,12749936,15000000,114739326,1,Emerging,Bronze,mobile,Low
768,769,1,154020442,150000000,600000000,3,Priority,Bronze,mobile,Low
786,787,1,29625390,26000000,121042809,1,Emerging,Bronze,mobile,Low
792,793,1,60486381,77000000,140429962,3,Priority,Gold,mobile,Low
825,826,1,55113444,30000000,109887540,1,Emerging,Silver,mobile,Low
935,936,1,329141488,150000000,208170765,3,Priority,Bronze,mobile,Low
956,957,0,12172955,67000000,132945928,3,Priority,Bronze,mobile,Low

In [22]:
print("Rows where balance is exactly 1 billion:")
display(
    df.loc[
        df["balance"] == 1000000000,
        cols_to_check
    ].head(20)
)

Rows where balance is exactly 1 billion:

,id,married,balance,monthly_ir,last_transaction_month,cluster_group,customer_segment,loyalty_level,digital_behavior,risk_segment
2157,2158,1,1000000000,190000000,0,4,Priority,Bronze,offline,Low
3136,3137,1,1000000000,122000000,0,4,Priority,Bronze,offline,Low
3893,3894,1,1000000000,97000000,0,4,Priority,Silver,offline,Low
4070,4071,0,1000000000,72000000,0,4,Priority,Bronze,offline,Low
5115,5116,1,1000000000,142000000,116644136,4,Priority,Bronze,mobile,Low
5282,5283,0,1000000000,83000000,0,4,Priority,Bronze,offline,Low
6220,6221,0,1000000000,112000000,0,4,Priority,Bronze,offline,Low
7017,7018,1,1000000000,152000000,0,4,Priority,Silver,offline,Low
10633,10634,2,1000000000,103000000,0,4,Priority,Bronze,offline,Low
10712,10713,3,1000000000,143000000,0,4,Priority,Silver,offline,Low
14048,14049,1,1000000000,63000000,0,4,Priority,Silver,offline,Low
19724,19725,0,1000000000,138000000,0,4,Priority,Bronze,offline,Low
19798,19799,1,1000000000,94000000,0,4,Priority,Bronze,offline,Low
19847,19848,1,1000000000,89000000,0,4,Priority,Bronze,offline,Low
20148,20149,0,1000000000,167000000,173713493,3,Priority,Bronze,mobile,Low
21255,21256,1,1000000000,122000000,0,4,Priority,Silver,offline,Low
25320,25321,0,1000000000,74000000,0,4,Priority,Bronze,offline,Low
26151,26152,1,1000000000,134000000,0,4,Priority,Bronze,offline,Low
27085,27086,2,1000000000,103000000,0,4,Priority,Silver,offline,Low
27786,27787,1,1000000000,124000000,0,4,Priority,Silver,offline,Low

In [23]:
# Check numerical columns for zero and negative values

numeric_cols = df.select_dtypes(include=["number"]).columns

for col in numeric_cols:
    print(f"\n========== {col} ==========")
    print("Zero values:", (df[col] == 0).sum())
    print("Negative values:", (df[col] < 0).sum())

========== id ==========
Zero values: 0
Negative values: 0

========== credit_sco ==========
Zero values: 0
Negative values: 0

========== age ==========
Zero values: 0
Negative values: 0

========== balance ==========
Zero values: 0
Negative values: 0

========== monthly_ir ==========
Zero values: 0
Negative values: 0

========== tenure_ye ==========
Zero values: 17768
Negative values: 0

========== married ==========
Zero values: 16480
Negative values: 0

========== nums_card ==========
Zero values: 0
Negative values: 0

========== nums_service ==========
Zero values: 0
Negative values: 0

========== last_transaction_month ==========
Zero values: 62824
Negative values: 0

========== engagement_score ==========
Zero values: 0
Negative values: 0

========== risk_score ==========
Zero values: 0
Negative values: 0

========== cluster_group ==========
Zero values: 0
Negative values: 0

In [24]:
# Check date columns

date_cols = ["created_date", "last_active_date"]

for col in date_cols:
    print(f"\n========== {col} ==========")
    print("Data Type:", df[col].dtype)
    print("Missing Values:", df[col].isna().sum())
    print("Unique Values:", df[col].nunique())
    print("Sample Values:")
    print(df[col].head(10).to_list())

========== created_date ==========
Data Type: str
Missing Values: 0
Unique Values: 1643
Sample Values:
['27/02/2025', '29/07/2021', '03/03/2021', '12/02/2022', '24/07/2022', '15/11/2021', '18/07/2021', '30/03/2021', '15/02/2023', '29/01/2022']

========== last_active_date ==========
Data Type: str
Missing Values: 0
Unique Values: 1614
Sample Values:
['03/04/2025', '14/05/2025', '10/09/2021', '04/03/2025', '06/08/2022', '29/01/2023', '23/07/2023', '02/05/2025', '06/05/2023', '20/06/2022']

In [25]:
# Check date validity

for col in ["created_date", "last_active_date"]:
    parsed_dates = pd.to_datetime(
        df[col],
        format="%d/%m/%Y",
        errors="coerce"
    )

    print(f"\n========== {col} ==========")
    print("Invalid dates:", parsed_dates.isna().sum())
    print("Minimum date:", parsed_dates.min())
    print("Maximum date:", parsed_dates.max())

========== created_date ==========
Invalid dates: 0
Minimum date: 2021-01-01 00:00:00
Maximum date: 2025-07-01 00:00:00

========== last_active_date ==========
Invalid dates: 0
Minimum date: 2021-01-16 00:00:00
Maximum date: 2025-07-01 00:00:00

In [26]:
# Convert date columns to datetime

df["created_date"] = pd.to_datetime(
    df["created_date"],
    format="%d/%m/%Y"
)

df["last_active_date"] = pd.to_datetime(
    df["last_active_date"],
    format="%d/%m/%Y"
)

print("Date conversion completed.\n")

print(df[["created_date", "last_active_date"]].dtypes)

display(df[["created_date", "last_active_date"]].head())

Date conversion completed.

created_date        datetime64[us]
last_active_date    datetime64[us]
dtype: object

  created_date last_active_date
0   2025-02-27       2025-04-03
1   2021-07-29       2025-05-14
2   2021-03-03       2021-09-10
3   2022-02-12       2025-03-04
4   2022-07-24       2022-08-06

In [27]:
# Check whether last_active_date is always on or after created_date

invalid_date_order = df[
    df["last_active_date"] < df["created_date"]
]

print("Rows where last_active_date is before created_date:",
      len(invalid_date_order))

if len(invalid_date_order) > 0:
    display(
        invalid_date_order[
            ["id", "created_date", "last_active_date"]
        ].head(20)
    )
else:
    print("Date relationship is valid for all customers.")

Rows where last_active_date is before created_date: 0
Date relationship is valid for all customers.

In [28]:
# Calculate days between customer creation and last activity

active_duration_days = (
    df["last_active_date"] - df["created_date"]
).dt.days

print("Minimum active duration:", active_duration_days.min(), "days")
print("Maximum active duration:", active_duration_days.max(), "days")
print("Average active duration:", round(active_duration_days.mean(), 2), "days")
print("Customers with 0 active days:", (active_duration_days == 0).sum())
print("Negative durations:", (active_duration_days < 0).sum())

Minimum active duration: 0 days
Maximum active duration: 1634 days
Average active duration: 410.34 days
Customers with 0 active days: 396
Negative durations: 0

In [29]:
# Check categorical columns for blank or whitespace-only values

categorical_cols = df.select_dtypes(include=["str"]).columns

for col in categorical_cols:
    blank_count = df[col].str.strip().eq("").sum()
    whitespace_count = df[col].str.contains(r"^\s+$", regex=True, na=False).sum()

    print(f"{col}:")
    print("  Blank values:", blank_count)
    print("  Whitespace-only values:", whitespace_count)

full_name:
  Blank values: 0
  Whitespace-only values: 0
gender:
  Blank values: 0
  Whitespace-only values: 0
occupation:
  Blank values: 0
  Whitespace-only values: 0
address:
  Blank values: 0
  Whitespace-only values: 0
origin_province:
  Blank values: 0
  Whitespace-only values: 0
customer_segment:
  Blank values: 0
  Whitespace-only values: 0
loyalty_level:
  Blank values: 0
  Whitespace-only values: 0
digital_behavior:
  Blank values: 0
  Whitespace-only values: 0
risk_segment:
  Blank values: 0
  Whitespace-only values: 0

In [30]:
# Check ID uniqueness

print("Total rows:", len(df))
print("Unique IDs:", df["id"].nunique())
print("Duplicate IDs:", df["id"].duplicated().sum())

if df["id"].is_unique:
    print("ID column is unique.")
else:
    print("ID column contains duplicates.")

Total rows: 80000
Unique IDs: 80000
Duplicate IDs: 0
ID column is unique.

In [31]:
# Check unique categorical values

categorical_cols = df.select_dtypes(include=["str"]).columns

for col in categorical_cols:
    print(f"\n========== {col} ==========")
    print(df[col].unique())

========== full_name ==========
<StringArray>
[     'Đặng Văn Vũ',     'Bùi Hữu Phúc',       'Lê Văn Mai',
 'Dương Trần Nhiên',   'Dương Thu Linh',    'Phạm Minh Lan',
   'Mai Ngọc Thành',  'Hoàng Kim Dương',      'Lê Gia Khoa',
  'Nguyễn Thu Linh',
 ...
   'Bùi Ngọc Hoàng',    'Lê Minh Trung',    'Đặng Thị Phúc',
   'Dương Gia Minh',   'Dương Đức Hưng',    'Dương Thu Huy',
  'Hoàng Thanh Bảo',   'Đặng Văn Trung',    'Mai Thanh Bảo',
    'Lê Ngọc Nhiên']
Length: 5100, dtype: str

========== gender ==========
<StringArray>
['male', 'female']
Length: 2, dtype: str

========== occupation ==========
<StringArray>
[         'Chủ Doanh nghiệp nhỏ',             'Nội trợ/Sinh viên',
          'Giáo viên/Giảng viên',          'Kỹ sư/Chuyên viên IT',
                       'Hưu trí', 'Nhân viên văn phòng/Công chức',
           'Kinh doanh/Bán hàng',              'Quản lý/Lãnh đạo',
             'Kế toán/Tài chính',            'Lao động phổ thông']
Length: 10, dtype: str

========== address ==========
<StringArray>
[          'Phường An Hội (BT)',        'Phường Bến Thành (Q1)',
        'Phường Hòa Bình (Q11)',                'Phường 7 (Q7)',
       'Phường Thắng Lợi (Q10)',        'Thị trấn Tân Túc (BC)',
       'Xã Xuân Thới Đông (HM)',              'Phường 14 (Q12)',
           'Xã Vĩnh Lộc A (BC)',         'Phường Tân Định (Q1)',
          'Phường 2 (Tân Bình)',      'Phường Quang Trung (GV)',
         'Phường Chợ Quán (Q5)',         'Phường Vĩnh Hội (Q4)',
      'Linh Trung (TP Thủ Đức)', 'Phường Tân Sơn Nhì (Tân Phú)']
Length: 16, dtype: str

========== origin_province ==========
<StringArray>
[  'TP. Hồ Chí Minh',          'Đồng Nai',        'Bình Dương',
         'Tỉnh khác',            'Hà Nội',           'Long An',
 'Bà Rịa - Vũng Tàu',           'Cần Thơ',        'Tiền Giang']
Length: 9, dtype: str

========== customer_segment ==========
<StringArray>
['Priority', 'Mass', 'Emerging', 'Affluent']
Length: 4, dtype: str

========== loyalty_level ==========
<StringArray>
['Bronze', 'Gold', 'Silver']
Length: 3, dtype: str

========== digital_behavior ==========
<StringArray>
['mobile', 'offline']
Length: 2, dtype: str

========== risk_segment ==========
<StringArray>
['Low', 'Medium']
Length: 2, dtype: str

In [32]:
# Check how married values relate to customer characteristics

married_check = (
    df.groupby("married")
      .agg(
          customers=("id", "count"),
          avg_age=("age", "mean"),
          avg_balance=("balance", "mean"),
          avg_credit_score=("credit_sco", "mean"),
          avg_engagement=("engagement_score", "mean")
      )
      .round(2)
)

display(married_check)

         customers  avg_age  avg_balance  avg_credit_score  avg_engagement
married
0            16480    42.97  54947822.42            683.47           31.63
1            53399    50.36  62021614.54            684.52           31.78
2             6096    53.62  65450822.82            684.16           31.58
3             4025    56.26  69126734.79            685.36           31.65

In [33]:
# Check last_transaction_month value ranges

bins = [
    -1,
    0,
    100,
    1000,
    10000,
    100000,
    1000000,
    10000000,
    100000000,
    600000000
]

labels = [
    "0",
    "1-100",
    "101-1K",
    "1K-10K",
    "10K-100K",
    "100K-1M",
    "1M-10M",
    "10M-100M",
    "100M-600M"
]

transaction_ranges = pd.cut(
    df["last_transaction_month"],
    bins=bins,
    labels=labels
)

print("Distribution of last_transaction_month:")
print(transaction_ranges.value_counts().sort_index())

Distribution of last_transaction_month:
last_transaction_month
0            62824
1-100            0
101-1K           0
1K-10K           0
10K-100K         0
100K-1M         51
1M-10M        4784
10M-100M     10638
100M-600M     1703
Name: count, dtype: int64

In [34]:
# Compare last_transaction_month with last_active_date

transaction_check = df[
    ["id", "last_transaction_month", "last_active_date"]
].copy()

display(
    transaction_check[
        transaction_check["last_transaction_month"] > 0
    ].head(20)
)

    id  last_transaction_month last_active_date
0    1                91038993       2025-04-03
1    2                 3255569       2025-05-14
7    8                 6462745       2025-05-02
16  17                31706109       2025-05-29
18  19                 2322197       2025-05-16
25  26                 5168697       2025-05-02
29  30                15971549       2025-06-11
30  31                17775197       2025-05-14
34  35                46492280       2025-05-14
36  37                15065550       2025-06-07
40  41                55062791       2025-04-19
44  45                 4415684       2025-04-23
47  48                23846449       2025-06-27
52  53                44355030       2025-06-24
55  56               103126977       2025-04-24
58  59                15416405       2025-05-29
65  66                 4030519       2025-04-19
69  70                59862993       2025-04-03
85  86                 6528612       2025-06-18
92  93               225966261       2025-04-07

In [35]:
# Check last transaction values for each last-active year

transaction_check["last_active_year"] = (
    transaction_check["last_active_date"].dt.year
)

display(
    transaction_check[
        transaction_check["last_transaction_month"] > 0
    ]
    .groupby("last_active_year")["last_transaction_month"]
    .agg(["count", "min", "max", "mean"])
    .round(2)
)

                  count     min        max        mean
last_active_year
2025              17176  500000  600000000  41135328.8

In [36]:
# Check relationship between last_transaction_month and digital_behavior

print(
    pd.crosstab(
        df["digital_behavior"],
        df["last_transaction_month"] > 0
    )
)

last_transaction_month  False  True
digital_behavior
mobile                      0  17176
offline                 62824      0

In [39]:
# Distribution of last_transaction_month for mobile customers

mobile_transactions = df[
    df["digital_behavior"] == "mobile"
]["last_transaction_month"]

print("Mobile customers:", len(mobile_transactions))
print("Unique values:", mobile_transactions.nunique())
print("Minimum:", mobile_transactions.min())
print("Maximum:", mobile_transactions.max())
print("Mean:", round(mobile_transactions.mean(), 2))
print("\nTop 15 values:")
print(mobile_transactions.value_counts().head(15))

Mobile customers: 17176
Unique values: 17131
Minimum: 500000
Maximum: 600000000
Mean: 41135328.8

Top 15 values:
last_transaction_month
600000000    38
500000        5
15774271      2
12152772      2
4727198       2
5592504       2
91038993      1
3255569       1
6462745       1
31706109      1
2322197       1
5168697       1
15971549      1
17775197      1
46492280      1
Name: count, dtype: int64

In [40]:
# Check relationships between last_transaction_month
# and other important numeric fields

cols = [
    "last_transaction_month",
    "balance",
    "monthly_ir",
    "engagement_score",
    "risk_score"
]

print(df[cols].corr()["last_transaction_month"].sort_values(ascending=False))

last_transaction_month    1.000000
engagement_score          0.544722
monthly_ir                0.246963
balance                   0.085760
risk_score               -0.424912
Name: last_transaction_month, dtype: float64

In [41]:
# Compare engagement score across last_transaction_month ranges

df["transaction_range"] = pd.cut(
    df["last_transaction_month"],
    bins=[
        -1, 0, 1_000_000, 10_000_000,
        100_000_000, 600_000_000
    ],
    labels=[
        "0",
        "1M or less",
        "1M-10M",
        "10M-100M",
        "100M-600M"
    ]
)

print(
    df.groupby(
        "transaction_range",
        observed=True
    )["engagement_score"]
    .agg(["count", "mean", "min", "max"])
    .round(2)
)

                   count   mean  min  max
transaction_range
0                  62824  20.37    7   45
1M or less            51  61.37   51   79
1M-10M              4784  66.21   48   97
10M-100M           10638  74.59   49  100
100M-600M           1703  85.04   60  100

In [42]:
# Remove temporary analysis column

df.drop(columns=["transaction_range"], inplace=True)

print("Temporary column removed.")
print("Current shape:", df.shape)

Temporary column removed.
Current shape: (80000, 26)

In [43]:
print("married value distribution:")
print(df["married"].value_counts().sort_index())

print("\nPercentage:")
print(
    (df["married"].value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

married value distribution:
married
0    16480
1    53399
2     6096
3     4025
Name: count, dtype: int64

Percentage:
married
0    20.60
1    66.75
2     7.62
3     5.03
Name: proportion, dtype: float64

In [44]:
print("Balance Statistics:")
print(df["balance"].describe())

print("\nUnique Balance Values:")
print(df["balance"].nunique())

print("\nTop 10 Most Frequent Balance Values:")
print(df["balance"].value_counts().head(10))

Balance Statistics:
count    8.000000e+04
mean     6.118320e+07
std      8.868620e+07
min      4.086630e+05
25%      1.462592e+07
50%      3.090276e+07
75%      6.960994e+07
max      1.000000e+09
Name: balance, dtype: float64

Unique Balance Values:
79920

Top 10 Most Frequent Balance Values:
balance
1000000000    50
36274615       2
9930029        2
43700745       2
58441232       2
15927405       2
12292938       2
29612098       2
6261095        2
7477733        2
Name: count, dtype: int64

In [45]:

print("Rows with balance = 1,000,000,000:")
print(df[df["balance"] == 1_000_000_000].head(20))

print("\nCount:")
print((df["balance"] == 1_000_000_000).sum())

print("\nCustomer Segment:")
print(df[df["balance"] == 1_000_000_000]["customer_segment"].value_counts())

print("\nRisk Segment:")
print(df[df["balance"] == 1_000_000_000]["risk_segment"].value_counts())

Rows with balance = 1,000,000,000:
          id         full_name  credit_sco  gender  age            occupation  \
2157    2158      Phạm Hữu Mai         800  female   42  Chủ Doanh nghiệp nhỏ
3136    3137      Lê Xuân Thảo         743  female   43      Quản lý/Lãnh đạo
3893    3894        Lê Hữu Huy         720    male   90      Quản lý/Lãnh đạo
4070    4071      Phạm Đức Ánh         660  female   73  Chủ Doanh nghiệp nhỏ
5115    5116       Mai Văn Mai         730  female   70  Chủ Doanh nghiệp nhỏ
5282    5283    Trần Ngọc Dũng         747    male   56      Quản lý/Lãnh đạo
6220    6221      Bùi Thị Minh         760    male   63      Quản lý/Lãnh đạo
7017    7018   Nguyễn Văn Ngọc         760  female   70  Chủ Doanh nghiệp nhỏ
10633  10634    Bùi Xuân Dương         777  female   67      Quản lý/Lãnh đạo
10712  10713  Nguyễn Thanh Yến         695  female   90  Chủ Doanh nghiệp nhỏ
14048  14049      Trần Hữu Chi         552  female   81  Chủ Doanh nghiệp nhỏ
19724  19725     Bùi Kim Trọng         709    male   67      Quản lý/Lãnh đạo
19798  19799   Hoàng Kim Hương         646  female   84      Quản lý/Lãnh đạo
19847  19848      Trần Gia Huy         703    male   74  Chủ Doanh nghiệp nhỏ
20148  20149     Dương Anh Chi         795  female   53  Chủ Doanh nghiệp nhỏ
21255  21256    Trần Hữu Quang         800    male   45      Quản lý/Lãnh đạo
25320  25321    Đặng Thu Quang         661    male   67  Kỹ sư/Chuyên viên IT
26151  26152    Hoàng Minh Yến         800  female   46      Quản lý/Lãnh đạo
27085  27086     Đặng Gia Phúc         743    male   66      Quản lý/Lãnh đạo
27786  27787  Dương Thanh Minh         770    male   90  Chủ Doanh nghiệp nhỏ

          balance  monthly_ir                       address  origin_province  \
2157   1000000000   190000000            Xã Vĩnh Lộc A (BC)         Đồng Nai
3136   1000000000   122000000           Phường 2 (Tân Bình)  TP. Hồ Chí Minh
3893   1000000000    97000000          Phường Tân Định (Q1)       Bình Dương
4070   1000000000    72000000          Phường Vĩnh Hội (Q4)  TP. Hồ Chí Minh
5115   1000000000   142000000  Phường Tân Sơn Nhì (Tân Phú)       Bình Dương
5282   1000000000    83000000         Phường Bến Thành (Q1)        Tỉnh khác
6220   1000000000   112000000           Phường 2 (Tân Bình)         Đồng Nai
7017   1000000000   152000000          Phường Vĩnh Hội (Q4)          Long An
10633  1000000000   103000000          Phường Chợ Quán (Q5)  TP. Hồ Chí Minh
10712  1000000000   143000000  Phường Tân Sơn Nhì (Tân Phú)           Hà Nội
14048  1000000000    63000000  Phường Tân Sơn Nhì (Tân Phú)       Bình Dương
19724  1000000000   138000000        Phường Thắng Lợi (Q10)  TP. Hồ Chí Minh
19798  1000000000    94000000            Phường An Hội (BT)          Long An
19847  1000000000    89000000       Phường Quang Trung (GV)           Hà Nội
20148  1000000000   167000000           Phường 2 (Tân Bình)  TP. Hồ Chí Minh
21255  1000000000   122000000            Xã Vĩnh Lộc A (BC)       Tiền Giang
25320  1000000000    74000000          Phường Chợ Quán (Q5)  TP. Hồ Chí Minh
26151  1000000000   134000000        Xã Xuân Thới Đông (HM)  TP. Hồ Chí Minh
27085  1000000000   103000000         Phường Hòa Bình (Q11)  TP. Hồ Chí Minh
27786  1000000000   124000000           Phường 2 (Tân Bình)       Bình Dương

       ...  last_transaction_month  created_date   exit  customer_segment  \
2157   ...                       0    2022-09-12  False          Priority
3136   ...                       0    2021-12-15  False          Priority
3893   ...                       0    2021-08-08  False          Priority
4070   ...                       0    2021-01-29  False          Priority
5115   ...               116644136    2025-01-15  False          Priority
5282   ...                       0    2021-06-05  False          Priority
6220   ...                       0    2023-11-24  False          Priority
7017   ...                       0    2021-12-13  False          Priority
10633  ...                       0    2022-02-06  False          Priority
10712  ...                       0    2021-10-23  False          Priority
14048  ...                       0    2021-04-08  False          Priority
19724  ...                       0    2021-10-03  False          Priority
19798  ...                       0    2021-06-25  False          Priority
19847  ...                       0    2021-04-27  False          Priority
20148  ...               173713493    2025-05-23  False          Priority
21255  ...                       0    2022-02-05  False          Priority
25320  ...                       0    2023-08-19  False          Priority
26151  ...                       0    2021-02-03  False          Priority
27085  ...                       0    2023-03-06  False          Priority
27786  ...                       0    2021-08-06  False          Priority

       engagement_score loyalty_level  digital_behavior risk_score  \
2157                 31        Bronze           offline     0.1450
3136                 31        Bronze           offline     0.1575
3893                 39        Silver           offline     0.1200
4070                 22        Bronze           offline     0.2350
5115                 80        Bronze            mobile     0.0275
5282                 28        Bronze           offline     0.1450
6220                 24        Bronze           offline     0.1700
7017                 35        Silver           offline     0.1325
10633                28        Bronze           offline     0.1575
10712                39        Silver           offline     0.1250
14048                45        Silver           offline     0.2680
19724                33        Bronze           offline     0.1200
19798                24        Bronze           offline     0.2240
19847                17        Bronze           offline     0.1825
20148                81        Bronze            mobile     0.0525
21255                42        Silver           offline     0.1200
25320                20        Bronze           offline     0.2215
26151                31        Bronze           offline     0.1575
27085                42        Silver           offline     0.1200
27786                39        Silver           offline     0.1200

       risk_segment cluster_group
2157            Low             4
3136            Low             4
3893            Low             4
4070            Low             4
5115            Low             4
5282            Low             4
6220            Low             4
7017            Low             4
10633           Low             4
10712           Low             4
14048           Low             4
19724           Low             4
19798           Low             4
19847           Low             4
20148           Low             3
21255           Low             4
25320           Low             4
26151           Low             4
27085           Low             4
27786           Low             4

[20 rows x 26 columns]

Count:
50

Customer Segment:
customer_segment
Priority    50
Name: count, dtype: int64

Risk Segment:
risk_segment
Low    50
Name: count, dtype: int64

In [46]:
print("Balance >= 100 Million:")
print((df["balance"] >= 100_000_000).sum())

print("\nBalance >= 500 Million:")
print((df["balance"] >= 500_000_000).sum())

print("\nBalance >= 900 Million:")
print((df["balance"] >= 900_000_000).sum())

print("\nTop 20 Highest Balances:")
print(
    df[["id", "balance", "customer_segment", "risk_segment"]]
    .sort_values("balance", ascending=False)
    .head(20)
)

Balance >= 100 Million:
13283

Balance >= 500 Million:
534

Balance >= 900 Million:
77

Top 20 Highest Balances:
          id     balance customer_segment risk_segment
27085  27086  1000000000         Priority          Low
35958  35959  1000000000         Priority          Low
77200  77201  1000000000         Priority          Low
36213  36214  1000000000         Priority          Low
67540  67541  1000000000         Priority          Low
67084  67085  1000000000         Priority          Low
67848  67849  1000000000         Priority          Low
6220    6221  1000000000         Priority          Low
76709  76710  1000000000         Priority          Low
7017    7018  1000000000         Priority          Low
32315  32316  1000000000         Priority          Low
46671  46672  1000000000         Priority          Low
25320  25321  1000000000         Priority          Low
50507  50508  1000000000         Priority          Low
36551  36552  1000000000         Priority          Low
61142  61143  1000000000         Priority          Low
10633  10634  1000000000         Priority          Low
2157    2158  1000000000         Priority          Low
19798  19799  1000000000         Priority          Low
33909  33910  1000000000         Priority          Low

In [47]:
print("Monthly IR Statistics:")
print(df["monthly_ir"].describe())

print("\nUnique Monthly IR Values:")
print(df["monthly_ir"].nunique())

print("\nTop 10 Most Frequent Monthly IR Values:")
print(df["monthly_ir"].value_counts().head(10))

Monthly IR Statistics:
count    8.000000e+04
mean     3.778820e+07
std      3.655107e+07
min      3.000000e+06
25%      1.400000e+07
50%      2.300000e+07
75%      4.700000e+07
max      2.160000e+08
Name: monthly_ir, dtype: float64

Unique Monthly IR Values:
209

Top 10 Most Frequent Monthly IR Values:
monthly_ir
13000000    2780
12000000    2763
14000000    2756
15000000    2658
11000000    2567
16000000    2514
10000000    2406
9000000     2293
17000000    2220
18000000    2114
Name: count, dtype: int64

In [48]:
print("Monthly IR by Customer Segment:")
print(
    df.groupby("customer_segment")["monthly_ir"]
      .agg(["count", "mean", "median", "min", "max"])
      .round(2)
)

Monthly IR by Customer Segment:
                  count          mean      median       min        max
customer_segment
Affluent          11210  4.425415e+07  43000000.0  10000000   59000000
Emerging          31662  2.240089e+07  22000000.0   6000000   34000000
Mass              21436  9.965339e+06  10000000.0   3000000   14000000
Priority          15692  1.022236e+08  99000000.0  14000000  216000000

In [49]:
print("Cluster Group Distribution:")
print(df["cluster_group"].value_counts().sort_index())

print("\nPercentage:")
print(
    (df["cluster_group"].value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

Cluster Group Distribution:
cluster_group
1    31017
2    33785
3     1696
4    13502
Name: count, dtype: int64

Percentage:
cluster_group
1    38.77
2    42.23
3     2.12
4    16.88
Name: proportion, dtype: float64

In [50]:
print("=== FINAL NUMERIC RANGE CHECK ===")

checks = {
    "credit_sco": (300, 900),
    "age": (0, 120),
    "tenure_ye": (0, 100),
    "nums_card": (0, 20),
    "nums_service": (0, 20),
    "engagement_score": (0, 100),
    "risk_score": (0, 1),
    "cluster_group": (1, 10)
}

for col, (min_val, max_val) in checks.items():
    below = (df[col] < min_val).sum()
    above = (df[col] > max_val).sum()

    print(
        f"{col}: below_min={below}, "
        f"above_max={above}"
    )

=== FINAL NUMERIC RANGE CHECK ===
credit_sco: below_min=0, above_max=0
age: below_min=0, above_max=0
tenure_ye: below_min=0, above_max=0
nums_card: below_min=0, above_max=0
nums_service: below_min=0, above_max=0
engagement_score: below_min=0, above_max=0
risk_score: below_min=0, above_max=0
cluster_group: below_min=0, above_max=0